[package]
name = "tmlapis"
version = "1.0.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.2", features = ["json"] }
reqwest = "0.11.11"
scraper = "0.13.0"
once_cell = "1.13.0"